#!/bin/bash

#set -x pipefail

tags_root=$(git rev-parse --show-toplevel)

if [[ -z $tags_root ]]; then
    tags_root=$(pwd)
    echo "Can't find git root, using ${tags_root} as tag root"
fi

#hs_files=$(find $tags_root -not -path '*/\.*' -not -path 'dist-newstyle' -not -path 'dist' -iname '*.hs' -o -iname '*.hsc' | tr "\n" " ")
hs_files=$(rg $tags_root --files --type haskell)

OUTDIR=${2:-tags}

fast-tags -o ${tags_root}/$OUTDIR --no-module-tags --nomerge $hs_files
