
# Dear old jj to remap Esc
hook global InsertChar j %{ try %{
  exec -draft hH <a-k>jj<ret> d
  exec <esc>
}}

# Load plug.kak and other stuff
source "%val{config}/plugins/plug.kak/rc/plug.kak"

# Language Server Protocol plugin
plug "kak-lsp/kak-lsp"

# List buffers and switch between them
plug "Delapouite/kakoune-buffers"

plug DERPSQUID9/kakoune-cyberpunk-neon theme config %{
    colorscheme cyberpunk-neon
}

# Enable the "80 characters" reminder
add-highlighter global/ column 81 default,red

# Highlighters

add-highlighter global/number-lines number-lines
add-highlighter global/show-matching show-matching
#add-highlighter global/show-whitespaces show-whitespaces

#UI
set-option -add global ui_options ncurses_status_on_top=yes
set-option -add global ui_options ncurses_assistant=cat
set-option -add global ui_options ncurses_set_title=no
